# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pick_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 210, 621, 182))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.in_text = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.in_text.setMaximumSize(QtCore.QSize(1000, 30))
        self.in_text.setObjectName("in_text")
        self.verticalLayout.addWidget(self.in_text)
        self.out_text = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.out_text.setMaximumSize(QtCore.QSize(1000, 30))
        self.out_text.setObjectName("out_text")
        self.verticalLayout.addWidget(self.out_text)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(660, 210, 111, 181))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.in_pick = QtWidgets.QToolButton(self.verticalLayoutWidget_2)
        self.in_pick.setMaximumSize(QtCore.QSize(60, 30))
        self.in_pick.setObjectName("in_pick")
        self.verticalLayout_2.addWidget(self.in_pick)
        self.out_pick = QtWidgets.QToolButton(self.verticalLayoutWidget_2)
        self.out_pick.setMaximumSize(QtCore.QSize(60, 30))
        self.out_pick.setObjectName("out_pick")
        self.verticalLayout_2.addWidget(self.out_pick)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(660, 400, 111, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.submit = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.submit.setMaximumSize(QtCore.QSize(100, 50))
        self.submit.setObjectName("submit")
        self.verticalLayout_3.addWidget(self.submit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.in_pick.setText(_translate("MainWindow", "..."))
        self.out_pick.setText(_translate("MainWindow", "..."))
        self.submit.setText(_translate("MainWindow", "确定"))
